Models/Project.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Configuration;
using System.Linq;
using System.Web;

namespace KillBug.Models
{
    public class Project
    {
        readonly ApplicationDbContext db = new ApplicationDbContext();

        public int Id { get; set; }

        [DisplayName("Project Name")]
        public string Name { get; set; }
        public string Description { get; set; }
        public string ProjectManagerId { get; set; }

        [DisplayFormat(DataFormatString = "{0:MMM dd, yyyy}")]
        public DateTime Created { get; set; }

        [DisplayFormat(DataFormatString = "{0:MMM dd, yyyy}")]
        public DateTime? Updated { get; set; }

        [DisplayName("Archived?")]
        public bool IsArchived { get; set; }

        public virtual ICollection<ApplicationUser> Users { get; set; }
        public virtual ICollection<Ticket> Tickets { get; set; }

        [NotMapped]
        public ApplicationUser ProjectManager { get { return db.Users.FirstOrDefault(u => u.Id == ProjectManagerId); } }

        public Project()
        {
            Users = new HashSet<ApplicationUser>();
            Tickets = new HashSet<Ticket>();
        }
    }
}

Models/Ticket.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace KillBug.Models
{
    public class Ticket
    {
        #region IDS
        public int Id { get; set; }
        public int ProjectId { get; set; }
        [DisplayName("Type")]
        public int TicketTypeId { get; set; }
        [DisplayName("Status")]
        public int TicketStatusId { get; set; }
        [DisplayName("Priority")]
        public int TicketPriorityId { get; set; }
        [DisplayName("Submitter")]
        public string SubmitterId { get; set; }
        [DisplayName("Developer")]
        public string DeveloperId { get; set; }
        #endregion

        #region DATA
        public string Title { get; set; }
        public string Description { get; set; }

        [DisplayFormat(DataFormatString = "{0:MMM dd, yyyy}")]
        public DateTime Created { get; set; }
        public DateTime? Updated { get; set; }
        public bool IsArchived { get; set; }
        #endregion

        #region NAVIGATION
        public virtual Project Project { get; set; }
        public virtual TicketType TicketType { get; set; }
        public virtual TicketStatus TicketStatus { get; set; }
        public virtual TicketPriority TicketPriority { get; set; }
        public virtual ApplicationUser Submitter { get; set; }
        public virtual ApplicationUser Developer { get; set; }
        public virtual ICollection<TicketAttachment> Attachments { get; set; }
        public virtual ICollection<TicketComment> Comments { get; set; }
        public virtual ICollection<TicketHistory> History { get; set; }
        #endregion

        public Ticket()
        {
            Attachments = new HashSet<TicketAttachment>();
            Comments = new HashSet<TicketComment>();
            History = new HashSet<TicketHistory>();
        }
    }
}

Models/TicketType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace KillBug.Models
{
    public class TicketType
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }

        public TicketType() { }
        public TicketType(string type)
        {
            Name = type;
        }
        public TicketType(string type, string description)
        {
            Name = type;
            Description = description;
        }
    }
}

Controllers/ChartsController.cs
using KillBug.Models;
using KillBug.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KillBug.Controllers
{
    public class ChartsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        //GET:Ticket Priority Data
        public JsonResult TicketPriorityChartData()
        {
            var data = new ChartData();
            data.KeyLabel = "# of Tickets";
            foreach (var priority in db.TicketPriorities.ToList())
            {
                var dataCount = db.Tickets.Where(t => t.TicketPriorityId == priority.Id).Count();
                data.Labels.Add(priority.Name);
                data.Data.Add(dataCount);
            }

            return Json(data, JsonRequestBehavior.AllowGet);
        }
        //GET:Ticket Status Data
        public JsonResult TicketStatusChartData()
        {
            var data = new ChartData();
            data.KeyLabel = "# of Tickets";
            foreach (var status in db.TicketStatus.ToList())
            {
                var dataCount = db.Tickets.Where(t => t.TicketStatusId == status.Id).Count();
                data.Labels.Add(status.Name);
                data.Data.Add(dataCount);
            }

            return Json(data);
        }
        //GET:Ticket Type Data
        public JsonResult TicketTypeChartData()
        {
            var data = new ChartData();
            data.KeyLabel = "# of Tickets";
            foreach (var type in db.TicketTypes.ToList())
            {
                var dataCount = db.Tickets.Where(t => t.TicketTypeId == type.Id).Count();
                data.Labels.Add(type.Name);
                data.Data.Add(dataCount);
            }
            return Json(data);
        }
    }
}

Controllers/DashboardController.cs
using KillBug.Classes;
using KillBug.Models;
using KillBug.ViewModels;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace KillBug.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private UserRolesHelper rolesHelper = new UserRolesHelper();
        private ProjectsHelper projHelper = new ProjectsHelper();

        // GET: Main
        public ActionResult Main()
        {
            ApplicationDbContext db = new ApplicationDbContext();
            UserRolesHelper rolesHelper = new UserRolesHelper();

            DashboardViewModel viewData = new DashboardViewModel()
            {
                TeamCount = db.Users.Count(),
                PMCount = rolesHelper.UsersInRole("Project Manager").Count,
                DevCount = rolesHelper.UsersInRole("Developer").Count,
                SubCount = rolesHelper.UsersInRole("Submitter").Count,
                ProjectsCount = db.Projects.Count(),
                TicketsCount = db.Tickets.Count(),
                NewTicketsCount = db.Tickets.Where(t => t.TicketStatus.Name == "New").Count(),
                CommentsCount = db.TicketComments.Count(),
                AttachmentsCount = db.TicketAttachments.Count(),
                HistoryCount = db.TicketHistories.Count()
            };

            return View(viewData);
        }

        // GET: Projects
        public ActionResult Projects()
        {
            var viewData = new ProjectsDashViewModel();

            if (User.IsInRole("Admin"))
            {
                viewData.ProjectManagerId = new SelectList(rolesHelper.UsersInRole("Project Manager"), "Id", "FullName");
            }
            return View(viewData);
        }

        // GET: Tickets
        public ActionResult Tickets()
        {
            var viewData = new TicketsDashViewModel();
            var myProjects = projHelper.ListUserProjects(User.Identity.GetUserId());

            if (myProjects.Count > 0)
            {
                viewData.ProjectId = new SelectList(myProjects, "Id", "Name");
                viewData.TicketTypeId = new SelectList(db.TicketTypes, "Id", "Name");
                viewData.TicketPriorityId = new SelectList(db.TicketPriorities, "Id", "Name");

                ViewBag.Create = true;
            } 
            else
            {
                ViewBag.Create = false;
            }

            var charts = new ChartsController();

            var serializer = new JavaScriptSerializer();
            viewData.JsonData = serializer.Serialize(charts.TicketPriorityChartData());


            viewData.PriorityData = charts.TicketPriorityChartData();
             
            return View(viewData);
        }
    }
}

Controllers/TicketsController.cs
using KillBug.Models;
using KillBug.Classes;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KillBug.ViewModels;

namespace KillBug.Controllers
{
    public class TicketsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private UserRolesHelper rolesHelper = new UserRolesHelper();
        private ProjectsHelper projHelper = new ProjectsHelper();
        private TicketsHelper ticketHelper = new TicketsHelper();
        private HistoryHelper historyHelper = new HistoryHelper();
        private NotificationHelper notificationHelper = new NotificationHelper();

        // GET: View Tickets
        [Authorize]
        public ActionResult ViewTickets(bool? AllTickets)
        {
            if(User.IsInRole("Admin") && AllTickets == true)
            {
                return View(db.Tickets.ToList());
            } else
            {
                return View(ticketHelper.ListMyTickets());
            }
        }
        // GET: Tickets/Details
        [Authorize]
        public ActionResult Details(int? id)
        {
            var userId = User.Identity.GetUserId();

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Ticket ticket = db.Tickets.Find(id);
            if (ticket == null)
            {
                return RedirectToAction("Error", new { message = TicketError.NullTicket });
            }

            if ((userId == ticket.SubmitterId) || (userId == ticket.DeveloperId) || (userId == ticket.Project.ProjectManagerId) || (ticket.Project.Users.Any(u => u.Id == userId)) || User.IsInRole("Admin"))
            {
                ViewBag.DeveloperId = new SelectList(ticketHelper.AssignableDevelopers(ticket.ProjectId), "Id", "FullNamePosition", ticket.DeveloperId);

                ViewBag.TicketTypeId = new SelectList(db.TicketTypes, "Id", "Name", ticket.TicketTypeId);
                ViewBag.TicketPriorityId = new SelectList(db.TicketPriorities, "Id", "Name", ticket.TicketPriorityId);
                ViewBag.TicketStatusId = new SelectList(db.TicketStatus, "Id", "Name", ticket.TicketStatusId);
                return View(ticket);
            }
            else
            {
                return RedirectToAction("Error", new { message = TicketError.NotAuthorizedToView });
            }
        }

        // GET: Tickets/History
        [Authorize]
        public ActionResult History()
        {
            //var userId = User.Identity.GetUserId();
            //var ticketHistories = new List<TicketHistory>();

            //if (User.IsInRole("Submitter"))
            //{
            //    ticketHistories = db.TicketHistories.Include(t => t.Ticket).Include(t => t.User).Where(t => t.Ticket.SubmitterId == userId).ToList();
            //}
            //return View(ticketHistories);
            return View(HistoryHelper.ListMyHistory());
        }

        // GET: Tickets/Create
        [Authorize(Roles = "Submitter")]
        public ActionResult Create()
        {
            var myProjects = projHelper.ListUserProjects(User.Identity.GetUserId());
            if (myProjects.Count > 0)
            {
                ViewBag.ProjectId = new SelectList(myProjects, "Id", "Name");
                ViewBag.TicketTypeId = new SelectList(db.TicketTypes, "Id", "Name");
                ViewBag.TicketPriorityId = new SelectList(db.TicketPriorities, "Id", "Name");

                return View(new Ticket());
            }
            return RedirectToAction("Error", new { message = TicketError.NoProjects });
        }

        // POST: Tickets/Create
        [HttpPost, ValidateAntiForgeryToken, Authorize(Roles = "Submitter")]
        public ActionResult Create([Bind(Include = "Id,ProjectId,TicketTypeId,TicketPriorityId,Title,Description")] Ticket ticket)
        {
            if (ModelState.IsValid)
            {
                ticket.SubmitterId = User.Identity.GetUserId();
                ticket.TicketStatusId = db.TicketStatus.FirstOrDefault(t => t.Name == "New").Id;
                ticket.Created = DateTime.Now;

                db.Tickets.Add(ticket);
                db.SaveChanges();

                //New Ticket Notification:
                var user = db.Users.Find(User.Identity.GetUserId());
                var projectName = db.Projects.Find(ticket.ProjectId).Name;
                Notification newNotification = new Notification
                {
                    Created = DateTime.Now,
                    TicketId = ticket.Id,
                    SenderId = user.Id,
                    Subject = "New Ticket",
                    Body = $"One of your projects has a new ticket!<br/>Ticket: { ticket.Title }<br/>Project: { projectName }<br/>By: { user.FullNamePosition }"
                };

                notificationHelper.NewTicketNotification(newNotification, ticket);

                return RedirectToAction("Details", new { id = ticket.Id });
            }

            var myProjects = projHelper.ListUserProjects(User.Identity.GetUserId());
            ViewBag.ProjectId = new SelectList(myProjects, "Id", "Name");
            ViewBag.TicketTypeId = new SelectList(db.TicketTypes, "Id", "Name");
            ViewBag.TicketPriorityId = new SelectList(db.TicketPriorities, "Id", "Name");

            return View(ticket);
        }

        // POST: Tickets/Edit/5
        [HttpPost, ValidateAntiForgeryToken, Authorize]
        public ActionResult Edit([Bind(Include = "Id,ProjectId,TicketTypeId,TicketStatusId,TicketPriorityId,DeveloperId,SubmitterId,Title,Description,Created,IsArchived")] Ticket ticket)
        {
            var userId = User.Identity.GetUserId();
            var project = db.Projects.Find(ticket.ProjectId);
            if ((userId == ticket.SubmitterId) || (userId == ticket.DeveloperId) || (userId == project.ProjectManagerId) || User.IsInRole("Admin"))
            {
                if (ModelState.IsValid)
                {
                    var oldTicket = db.Tickets.AsNoTracking().FirstOrDefault(t => t.Id == ticket.Id);

                    ticket.Updated = DateTime.Now;
                    db.Entry(ticket).State = EntityState.Modified;
                    db.SaveChanges();

                    var newTicket = db.Tickets.AsNoTracking().FirstOrDefault(t => t.Id == ticket.Id);

                    historyHelper.CreateHistory(oldTicket, ticket);

                    notificationHelper.ManageNotifications(oldTicket, newTicket);

                    RedirectToAction("Details", new { id = ticket.Id });
                }

                ViewBag.DeveloperId = new SelectList(ticketHelper.AssignableDevelopers(ticket.ProjectId), "Id", "FullNamePosition", ticket.DeveloperId);

                ViewBag.TicketTypeId = new SelectList(db.TicketTypes, "Id", "Name", ticket.TicketTypeId);
                ViewBag.TicketPriorityId = new SelectList(db.TicketPriorities, "Id", "Name", ticket.TicketPriorityId);
                ViewBag.TicketStatusId = new SelectList(db.TicketStatus, "Id", "Name", ticket.TicketStatusId);
                return RedirectToAction("Details", new { id = ticket.Id });
            }
            else
            {
                return RedirectToAction("Error", new { message = TicketError.NotAuthorizedToEdit });
            }
        }

        public ActionResult Error(TicketError? message)
        {
            ViewBag.ErrorMessage = message == TicketError.NoProjects ? "You are not assigned to any Projects.<br/><br/>Please contact your superior to be assigned to a new Project."
                : message == TicketError.NotAuthorizedToEdit ? "You are not authorized to Edit this Ticket."
                : message == TicketError.NotAuthorizedToComment ? "You are not authorized to leave Comments on this Ticket."
                : message == TicketError.NotAuthorizedToUpload ? "You are not authorized to upload Attachments to this Ticket."
                : message == TicketError.NotAuthorizedToView ? "You are not authorized to view this Ticket."
                : message == TicketError.NullTicket ? "There has been an error retrieving the ticket. Please alert your superior."
                : "There has been an error. Please try again and alert management if it persists.";

            return View();
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public enum TicketError
        {
            NoProjects,
            NotAuthorizedToEdit,
            NotAuthorizedToComment,
            NotAuthorizedToUpload,
            NotAuthorizedToView,
            NullTicket
        }
    }
}

Views/Dashboard/Projects.cshtml
@using KillBug.ViewModels
@using Microsoft.AspNet.Identity

@model ProjectsDashViewModel

@{
    ViewBag.Title = "Dashboard: Projects";
}

@if (User.IsInRole("Admin") || User.IsInRole("Project Manager"))
{
    <div class="row shortcut-bar">
        <div class="col-auto">
            <div class="shortcut btn" id="shc-create-project">Create Project&nbsp;<i class="fas fa-plus"></i></div>
        </div>
    </div>

    <div class="row shortcut-row">
        <div class="col-6" id="create-project">
            <div class="block">
                <div class="title row no-gutters mb-0">
                    <div class="col-auto"><strong>Create Project</strong></div>
                    <div class="col-auto ml-auto"><i class="fas fa-lg fa-chevron-up btn btn-block-minimize"></i></div>
                    <div class="col-auto"><i class="fas fa-lg fa-times btn btn-block-close"></i></div>
                </div>
                <div class="block-body collapsable">
                    @using (Html.BeginForm("Create", "Projects"))
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="form-group">
                                <div class="col-auto">
                                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "form-control-label" })
                                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-auto">
                                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "form-control-label" })
                                    @Html.TextAreaFor(model => model.Description, new { @class = "form-control", rows="4" })
                                </div>
                            </div>

                            @if (User.IsInRole("Admin"))
                            {
                                <div class="form-group">
                                    <div class="col-auto">
                                        @Html.Label("Project Manager", new { @class = "form-control-label" })
                                        @Html.DropDownList("ProjectManagerId", null, new { @class = "form-control" })
                                    </div>
                                </div>
                            }
                            else
                            {
                                @Html.Hidden("ProjectManagerId", User.Identity.GetUserId())
                            }

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Create" class="btn btn-primary" />
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
}

<h4>Coming Soon!</h4>

@section Scripts{
    <script>
        //ACTIVE SIDE MENU BUTTON
        $('#ProjectsDashboard').addClass('active')
        $('#ProjectsMenu').click()

        //BLOCK CONTROL BUTTONS
        $('.btn-block-minimize').on("click", function (e) {
            $(e.currentTarget).toggleClass(['fa-chevron-up', 'fa-chevron-down'])
            $(e.currentTarget).closest('.block').children('.collapsable').slideToggle()
        });
        $('.btn-block-close').on("click", function (e) {
            $(e.currentTarget).closest('.block').parent().hide()
        });

        //SHORTCUT BUTTONS
        $('#create-project').hide()
        $('#shc-create-project').on("click", () => {
            $('#shortcut-row').prepend($('#create-project'))
            //$('#create-project').removeClass('d-none')
            $('#create-project').slideDown()
        })

    </script>
}

Views/Dashboard/Tickets.cshtml
@using KillBug.ViewModels
@model TicketsDashViewModel

@{
    ViewBag.Title = "Dashboard: Tickets";
}

@if (ViewBag.Create)
{
    <div class="row shortcut-bar">
        <div class="col-auto">
            <div class="shortcut btn" id="shc-create-ticket">Create Ticket&nbsp;<i class="fas fa-plus"></i></div>
        </div>
    </div>
    <div class="row shortcut-row">
        <div class="col-6 d-none" id="create-ticket">
            <div class="block">
                <div class="title row no-gutters mb-0">
                    <div class="col-auto"><strong>Create Ticket</strong></div>
                    <div class="col-auto ml-auto"><i class="fas fa-lg fa-chevron-up btn btn-block-minimize"></i></div>
                    <div class="col-auto"><i class="fas fa-lg fa-times btn btn-block-close"></i></div>
                </div>
                <div class="block-body collapsable">
                    @using (Html.BeginForm("Create", "Tickets"))
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "form-control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "form-control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.TextAreaFor(model => model.Description, new { @class = "form-control", rows = "3" })
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-md-4">
                                    @Html.LabelFor(model => model.ProjectId, "ProjectId", htmlAttributes: new { @class = "form-control-label" })
                                    @Html.DropDownListFor(model => model.ProjectId, null, htmlAttributes: new { @class = "form-control" })
                                </div>
                                <div class="col-md-3">
                                    @Html.LabelFor(model => model.TicketTypeId, htmlAttributes: new { @class = "form-control-label" })
                                    @Html.DropDownListFor(model => model.TicketTypeId, null, htmlAttributes: new { @class = "form-control" })
                                </div>
                                <div class="col-md-3">
                                    @Html.LabelFor(model => model.TicketPriorityId, htmlAttributes: new { @class = "form-control-label" })
                                    @Html.DropDownListFor(model => model.TicketPriorityId, null, htmlAttributes: new { @class = "form-control" })
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Create" class="btn btn-primary" />
                                </div>
                            </div>
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
}

<!-- CHARTS ROW -->
<div class="row">
    <div class="col-md-4 col-sm-6">
        <div class="block">
            <div class="title row no-gutters mb-0">
                <div class="col-10"><strong class="d-block">Ticket Priority</strong></div>
                <div class="ml-auto"><i class="fas fa-lg fa-chevron-up btn btn-block-minimize" id="collapse-ticket-priorities"></i></div>
            </div>
            <div class="block-body collapsable">
                <canvas id="priority-bar"></canvas>
            </div>
        </div>
    </div>
    <div class="col-md-4 col-sm-6">
        <div class="block">
            <div class="title row no-gutters mb-0">
                <div class="col-10"><strong class="d-block">Ticket Types</strong></div>
                <div class="ml-auto"><i class="fas fa-lg fa-chevron-up btn btn-block-minimize" id="collapse-ticket-types"></i></div>
            </div>
            <div class="block-body collapsable">
                <canvas id="types-polar"></canvas>
            </div>
        </div>
    </div>
    <div class="col-md-4 col-sm-6">
        <div class="block">
            <div class="title row no-gutters mb-0">
                <div class="col-10"><strong class="d-block">Ticket Status</strong></div>
                <div class="ml-auto"><i class="fas fa-lg fa-chevron-up btn btn-block-minimize" id="collapse-ticket-status"></i></div>
            </div>
            <div class="block-body collapsable">
                <canvas id="types-doughnut"></canvas>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
        //ACTIVATE SIDE MENU BUTTON
        $('#TicketsMenu').click()
        $('#TicketsDashboard').addClass('active')

        //BLOCK CONTROL BUTTONS
        $('.btn-block-minimize').on("click", function (e) {
            $(e.currentTarget).toggleClass(['fa-chevron-up', 'fa-chevron-down'])
            $(e.currentTarget).closest('.block').children('.collapsable').slideToggle()
        });
        $('.btn-block-close').on("click", function (e) {
            $(e.currentTarget).closest('.block').parent().toggleClass('d-none')
        });

        //SHORTCUT BUTTONS
        $('#shc-create-ticket').on("click", () => {
            $('#create-ticket').removeClass('d-none')
            $('#shortcut-row').prepend($('#create-ticket'))
        })

        $.getJSON("@Url.Action("TicketPriorityChartData", "Charts")", function (response) {
            var ctx = document.getElementById('priority-bar').getContext('2d');
            var myChart = new Chart(ctx, {
                type: 'bar',
                data: {
                    labels: response.Labels,
                    datasets:
                        [{
                            label: response.KeyLabel,
                            data: response.Data,
                            backgroundColor: response.Options.BackgroundColors,
                            borderColor: response.Options.BorderColors,
                            borderWidth: response.Options.BorderWidth
                        }]
                },
                options: {
                    scales: {
                        yAxes: [{
                            ticks: {
                                beginAtZero: true
                            }
                        }]
                    }
                }
            });
        });


    </script>
}